const scriptsData = [
    {
        name: "VHub V2",
        image: "VHub2/1.png",
        about: "Script ESP, WORLD-HACK, PLAYER-HACK, SUMMON, FUN",
        data: "19.06.2026",
        universal: "true",
        verificate: "true",
        executors: "false",
        vhub: "true",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/VuanHubs/VHubs/refs/heads/main/VHubV2.lua'))()",
        url: ""
    },
    {
        name: "Infinite Yield",
        image: "IY/1.png",
        about: "Admin Tools for roblox",
        data: "06.05.2022",
        universal: "true",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()",
        url: ""
    },
    {
        name: "VSTK V2",
        image: "VSTKv2/1.png",
        about: "Script for Survival the Killer - ESP, REVIVE, WORLD-HACK, ANTI TRAP",
        data: "27.06.2026",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "true",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/AuriXDev/VHubs/refs/heads/main/games/SurvivarTheKiller.lua'))()",
        url: ""
    },
    {
        name: "MM2 | Vertex",
        image: "MM2vertex/1.png",
        about: "Powerful script for Myrder Mystery 2",
        data: "02.07.2026",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/yoursvexyyy/vexx/main/loader'))()",
        url: ""
    },
    {
        name: "Xeno",
        image: "executors/xeno.png",
        about: "Xeno - most popular free and keyless executor",
        data: "Undetect",
        universal: "false",
        verificate: "true",
        executors: "true",
        vhub: "false",
        keysystem: "false",
        script: "",
        url: "https://www.xeno.now/download"
    },
    {
        name: "AimBot by v3lnx",
        image: "AIMbyV3LNX/1.png",
        about: "Universal AIM assist with ESP and CFG",
        data: "02.07.2026",
        universal: "true",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/zzsiren/Megaskid.wtf/refs/heads/main/script.lua', true))()",
        url: ""
    },
    {
        name: "FNAF: Eternal Night",
        image: "FNAF-EN/1.png",
        about: "Script for FNAF: External Night - ESP, TELEPORT and MORE features",
        data: "04.07.2026",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "true",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/VuanHubs/VHubs/refs/heads/main/games/fnaf%3Aen.lua'))()",
        url: ""
    },
    {
        name: "VSTK V1.4",
        image: "VSTKv1.4/1.png",
        about: "Script for Survival the Killer (version 1.4) - ESP, REVIVE, WORLD-HACK",
        data: "19.06.2026",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "true",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/AuriXDev/VHubs/refs/heads/main/old/STK_V1_4.lua'))()",
        url: ""
    },
    {
        name: "Wave",
        image: "executors/wave.png",
        about: "Wave - best paid executor",
        data: "Undetect",
        universal: "false",
        verificate: "true",
        executors: "true",
        vhub: "false",
        keysystem: "true",
        script: "",
        url: "https://getwave.gg"
    },
    {
        name: "Fly | By me_ozonYT",
        image: "fly/1.jpg",
        about: "Just fly gui",
        data: "20.04.2023",
        universal: "true",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring('\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\40\39\104\116\116\112\115\58\47\47\103\105\115\116\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\109\101\111\122\111\110\101\89\84\47\98\102\48\51\55\100\102\102\57\102\48\97\55\48\48\49\55\51\48\52\100\100\100\54\55\102\100\99\100\51\55\48\47\114\97\119\47\101\49\52\101\55\52\102\52\50\53\98\48\54\48\100\102\53\50\51\51\52\51\99\102\51\48\98\55\56\55\48\55\52\101\98\51\99\53\100\50\47\97\114\99\101\117\115\37\50\53\50\48\120\37\50\53\50\48\102\108\121\37\50\53\50\48\50\37\50\53\50\48\111\98\102\108\117\99\97\116\111\114\39\41\44\116\114\117\101\41\41\40\41\10\10')()",
        url: ""
    },
    {
        name: "Crown Softworks | Hub",
        image: "csh/1.png",
        about: "Support Deadline, Flick, Recoil, Evade, Bite by night",
        data: "24.04.2026 ",
        universal: "true",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "true",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/ExclusiveVersionGithubIsLoaded/CrownSoftworks/refs/heads/main/link'))()",
        url: ""
    },
    {
        name: "Arsenal | Luigi",
        image: "../assets/1.png",
        about: "Script for Arsenal esp and aim",
        data: "20.10.2025",
        universal: "false",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/Luigi4k85/Arsenal-v5.3/refs/heads/main/Arsenal%20v5.3'))()",
        url: ""
    },
    {
        name: "BloxStrike",
        image: "../assets/1.png",
        about: "Cheat for BloxStrike. ESP Hitbox expander Blue Outline Speed Boost No Recoil",
        data: "30.06.2026",
        universal: "false",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "true",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/DmitriyGnatyk/bx_public/refs/heads/main/1.lua'))()",
        url: ""
    },
    {
        name: "Blox Fruits",
        image: "1BF/1.png",
        about: "Auto eggs, fruits, levels, chests, berries, bounty, fish, sea events and more",
        data: "11.04.2026",
        universal: "false",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "true",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/Huylovemy/Bearhudz/refs/heads/main/Bearhud.lua'))()",
        url: ""
    },
    {
        name: "Lumber Tycoon 2",
        image: "1lt2/1.jpg",
        about: "Get Tree, Teleports, Player Features",
        data: "27.10.2024",
        universal: "false",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/DevKron/Kron_Hub/refs/heads/main/version_1.0'))",
        url: ""
    },
    {
        name: "Speacter",
        image: "../assets/1.png",
        about: "ESP AUTO-evidence",
        data: "29.10.2024",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet(('https://pastebin.com/raw/uPrFkC6t')))()",
        url: ""
    },
    {
        name: "Speacter 2",
        image: "../assets/1.png",
        about: "None",
        data: "29.10.2024",
        universal: "false",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game.HttpGet(game, 'https://raw.githubusercontent.com/zuhnosu/roblox-scripts/main/linsher/specter2.lua', true))()",
        url: ""
    },
    {
        name: "Blox Fruit | Teach hub",
        image: "../assets/1.png",
        about: "AUTO Fruit, AUTO Chests",
        data: "27.10.2024",
        universal: "false",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "true",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/Scriptztyz/robloxscript/main/Teach_Hub'))()",
        url: ""
    },
    {
        name: "BABFT",
        image: "../assets/1.png",
        about: "Small script with autofarm and the inclusion of promo codes",
        data: "27.10.2024",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://api.luarmor.net/files/v3/loaders/2529a5f9dfddd5523ca4e22f21cceffa.lua'))()",
        url: ""
    },
    {
        name: "Plutonium HUB",
        image: "../assets/1.png",
        about: "Big script HUB",
        data: "22.10.2024",
        universal: "true",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/PawsThePaw/Plutonium.AA/refs/heads/main/Versions%202/V3.7.2.txt', true))()",
        url: ""
    },
    {
        name: "Legends Of Speed",
        image: "../assets/1.png",
        about: "Auto Farm, Auto Speed, Auto Rebirth",
        data: "8.10.2024",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://gitlab.com/madsbrriinckbastholm/team-skeet/-/raw/main/Legends-Of-Speed'))()",
        url: ""
    },
    {
        name: "Piggy",
        image: "../assets/1.png",
        about: "ESP, Anti Trap and more",
        data: "19.02.2025",
        universal: "false",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "true",
        script: "loadstring(game:HttpGet(('https://raw.githubusercontent.com/BaconBABA/T-HUB/main/Main'),true))()",
        url: ""
    },
    {
        name: "Universal HUB",
        image: "../assets/1.png",
        about: "None",
        data: "09.05.2023",
        universal: "true",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/Podroka626/Scripts/main/Universal'))()",
        url: ""
    },
    {
        name: "GamesHUB Destroyer",
        image: "../assets/1.png",
        about: "Powerful HUB",
        data: "09.05.2023",
        universal: "true",
        verificate: "true",
        executors: "false",
        vhub: "false",
        keysystem: "true",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/TakeModzz/Games-HUB-Destroyer-V4/main/Games%20HUB%20Destroyer%20V4'))()",
        url: ""
    },
    {
        name: "Vanish Hub",
        image: "vanhub/1.png",
        about: "ESP AIM Anti-AIM WORLD-HACK",
        data: "28.02.2026",
        universal: "true",
        verificate: "false",
        executors: "false",
        vhub: "false",
        keysystem: "false",
        script: "loadstring(game:HttpGet('https://raw.githubusercontent.com/Gregory909/scripts/refs/heads/main/Universal.lua'))()",
        url: ""
    },
//    {
//        name: "",
//        image: "../assets/1.png",
//        about: "",
//        data: "29.10.2024",
//        universal: "",
//        verificate: "",
//       executors: "false",
//        vhub: "false",
//        script: "",
//        url: ""
//    },
];
